[package]
name = "goose"
version = "0.5.9"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"
description = "A load testing tool inspired by Locust."
homepage = "https://github.com/jeremyandrews/goose"
documentation = "https://docs.rs/goose/"
repository = "https://github.com/jeremyandrews/goose"
readme = "README.md"
keywords = ["loadtesting", "performance", "web", "framework", "tool"]
license = "Apache-2.0"

[dependencies]
#goose_codegen = { path = "goose_codegen" }
ctrlc = "3.1"
http = "0.2"
libzmq = "0.2"
log = "0.4"
num_cpus = "1.0"
num-format = "0.4"
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "cookies", "json"] }
simplelog = "0.7"
structopt = "0.3"
url = "2.1"

[dev-dependencies]
scraper = "0.11.0"
select = "0.4"
