[package]
name = "goose"
version = "0.1.0"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"

[dependencies]
goose_codegen = { path = "goose_codegen" }
structopt = "0.3"
regex = "1"
simplelog = "0.7"
log = "0.4"
reqwest = "0.10"
