[package]
name = "goose"
version = "0.5.1"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"
description = "A lood testing tool based on Locust."
homepage = "https://github.com/jeremyandrews/goose"
documentation = "https://docs.rs/goose/"
repository = "https://github.com/jeremyandrews/goose"
readme = "README.md"
keywords = ["loadtesting", "performance", "web", "framework", "tool"]
license = "BSD-2-Clause"

[dependencies]
#goose_codegen = { path = "goose_codegen" }
ctrlc = "3.1"
http = "0.2"
log = "0.4"
num_cpus = "1.0"
num-format = "0.4"
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", features = ["blocking"] }
structopt = "0.3"
simplelog = "0.7"
url = "2.1"
