[package]
name = "goose"
version = "0.2.0"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"

[dependencies]
#goose_codegen = { path = "goose_codegen" }
ctrlc = "3.1"
http = "0.2"
log = "0.4"
num_cpus = "1.0"
num-format = "0.4"
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", features = ["blocking"] }
structopt = "0.3"
simplelog = "0.7"
