[package]
name = "goose_codegen"
version = "0.1.0"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"

[lib]
crate_type = ["proc-macro"]

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"

