name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify code formatting
      run: cargo fmt -- --check
    - name: Verify code style
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
